### ISSUE TITLE
Bug in field type "Taxonomy Terms"

### ISSUE THREAD

**Issue by sebastienserre** [acf-extended/ACF-Extended#73] opened 2021-02-26 07:22 UTC
**Describe the bug**
When a Taxonomy Terms fields is created with check box I have a display bug in Content edit page:
![terms-checkbox](https://user-images.githubusercontent.com/3902621/109268359-3f7c0d80-780b-11eb-8d7e-dea5f743a4c4.png)

If I modifiy from Checkbox to Radio:
![terms-radio](https://user-images.githubusercontent.com/3902621/109268500-76522380-780b-11eb-9583-cc9593f27ff3.png)

If I add this field group into a front end form (with ACF Extended):
![terms-form](https://user-images.githubusercontent.com/3902621/109268626-a0a3e100-780b-11eb-9aae-a7ed0f2db0b5.png)

**WordPress & ACF**
WordPress version: 5.6.2
ACF Pro version:  5.9.5
ACF Extended: 0.8.7.6

**Comment by acf-extended** [comment] 2021-02-27 21:47
Hello,

Thanks for the feedback! I'll split your report in two part.

- Changing field type
I can't seem to reproduce the issue on my local setup. Everything works fine here when switching between checkbox & radio. I noticed that your Taxonomy Names seem to have weird duplicated names "categoriecategorie".

Have you injected a custom code in the field render? I would advice to not inject JS/PHP there, since the Taxonomy Terms (and "Grouped" radio/checkbox feature from ACF Extended) use some PHP+JS method to create those "Grouped Titles". This may be the cause of the problem.

![Base-28](https://user-images.githubusercontent.com/53943543/109401090-f502aa00-794c-11eb-8fca-f64f0325a1d7.jpg)
![Base-29](https://user-images.githubusercontent.com/53943543/109401095-f7650400-794c-11eb-940f-f43614e16e99.jpg)

- Front-end display
This issue will be fixed in the patch. Here is the Trello card: https://trello.com/c/uManW6a5/515-field-checkbox-radio-fixed-title-group-options-not-working-on-front-end

Have a nice day!

Regards.

**Comment by acf-extended** [comment] 2021-03-20 13:06
Hello,

Just a heads up to let you that the latest 0.8.8 Update fixed this issue.

Have a nice day!

Regards.

**Closed by acf-extended** 2021-03-20 13:06 UTC
Labels: Fixed in next patch, need information
